[project]
name = 'Clinical-Trial-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-collection]
path = 'contracts/data-collection.clar'
clarity_version = 2
epoch = 2.5

[contracts.drug-supply]
path = 'contracts/drug-supply.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
